### ISSUE TITLE
Dt scaling for EAS calculation example

### ISSUE THREAD

**Issue by glavrentiadis** [arkottke/pykooh#2]
Hi Albert:

Do the amplitude spectra in  `example.ipynb` need to be scaled by dt to be in units of velocity?

Box 4: `fourier_amps =  trace.stats['delta'] * np.abs(np.fft.rfft(trace.data))`, and 
Box 14: `fourier_amps = time_step * np.fft.rfft(accels, axis=0)`

Thanks,
Greg

**Comment by arkottke** [comment]
Yes, they should be normalized by the time step. Thanks for catching that.
